/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xsystem;

import java.util.ArrayList;

import org.apache.log4j.BasicConfigurator;

import xsystem.learning.LearningModel;

public class Library {
    public boolean someLibraryMethod() {
        BasicConfigurator.configure();
        String path = "src/main/resources/LearningData";
        String outputFile = "src/main/resources/Learned/LearnedXStructs.json";
        LearningModel l = new LearningModel();
        // l.learnStructs(path, outputFile);
        ArrayList<String> s = new ArrayList<>();
        s.add("Christopher");
        s.add("Christopher");
        System.out.println(l.labelAssignment(s));
        return true;
    }
}