/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xsystem.ng;

import xsystem.ng.Layers.Symbol;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("Works!");
        Symbol x = new Symbol('x');
        System.out.println(x);
        Symbol y = x.addChar('1');
        System.out.println(y);
        return true;
    }
}
